#ifndef WEB_PAGE_H
#define WEB_PAGE_H

const char* index_html = 
"<!DOCTYPE html>"
"<html>"
"<head>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'>"
    "<title>ESP32 BMS Flasher</title>"
    "<style>"
        "* { margin: 0; padding: 0; box-sizing: border-box; }"
        "body { font-family: 'Segoe UI', sans-serif; background: #1a1a2e; color: #fff; padding: 20px; }"
        ".container { max-width: 800px; margin: 0 auto; }"
        "h1 { text-align: center; color: #00ff88; margin-bottom: 20px; font-size: 24px; }"
        ".card { background: #252525; padding: 20px; border-radius: 10px; border: 1px solid #333; margin-bottom: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }"
        "h2 { font-size: 18px; border-bottom: 1px solid #444; padding-bottom: 10px; margin-bottom: 15px; color: #ccc; }"
        "textarea { width: 100%; padding: 12px; background: #161625; color: #0f0; border: 1px solid #444; border-radius: 5px; font-family: monospace; resize: vertical; margin-top: 10px; }"
        ".file-input-wrapper { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; }"
        "input[type='file'] { background: #333; color: #fff; padding: 8px; border-radius: 5px; border: 1px solid #555; width: 100%; cursor: pointer; }"
        ".btn { background: #00ff88; color: #000; padding: 12px; border: none; border-radius: 5px; cursor: pointer; width: 100%; font-weight: bold; font-size: 16px; margin-top: 15px; transition: 0.2s; }"
        ".btn:hover { background: #00cc6a; }"
        ".btn:disabled { background: #555; color: #888; cursor: not-allowed; }"
        ".btn-red { background: #ff4444; color: white; margin-top: 10px; }"
        ".btn-red:hover { background: #cc0000; }"
        ".progress-bg { width: 100%; background-color: #444; border-radius: 5px; margin-top: 15px; height: 30px; overflow: hidden; position: relative; }"
        ".progress-fill { width: 0%; height: 100%; background-color: #00ff88; transition: width 0.5s; }"
        ".progress-text { position: absolute; width: 100%; height: 100%; top: 0; left: 0; display: flex; align-items: center; justify-content: center; color: #fff; font-weight: bold; mix-blend-mode: difference; }"
        ".status-row { display: flex; justify-content: space-between; margin-top: 10px; font-family: monospace; color: #aaa; font-size: 14px; }"
        ".highlight { color: #00ff88; }"
    "</style>"
"</head>"
"<body>"
    "<div class='container'>"
        "<h1>Vega BMS Updater</h1>"
        "<div class='card'>"
            "<h2>1. Upload Firmware as txt or paste in the box</h2>"
            "<div class='file-input-wrapper'>"
                "<input type='file' id='fileInput' accept='.txt,.hex,.csv'>"
            "</div>"
            "<textarea id='hexInput' rows='8' placeholder='Select a file above OR Paste Data Here...'></textarea>"
            "<button class='btn' id='uploadBtn' onclick='uploadFirmware()'>Upload & Verify</button>"
            "<div class='status-row'>"
                "<span>Status: <span id='uploadStatus' class='highlight'>Idle</span></span>"
                "<span>RAM Usage: <span id='ramSize'>0</span> bytes</span>"
            "</div>"
        "</div>"
        "<div class='card'>"
            "<h2>2. Update the BMS</h2>"
            "<p style='color:#888; font-size: 13px; margin-bottom: 10px;'>Ensure CAN bus is connected before starting.</p>"
            "<button class='btn' id='flashBtn' onclick='startFlash()' disabled>Start Update</button>"
            "<div class='progress-bg'>"
                "<div id='progressBar' class='progress-fill'></div>"
                "<div id='progressText' class='progress-text'>0%</div>"
            "</div>"
            "<div class='status-row'>"
                "<span>System: <span id='sysState' class='highlight'>Idle</span></span>"
                "<span>Progress: <span id='sentBytes'>0</span> / <span id='totalBytes'>0</span></span>"
            "</div>"
            // RESET BUTTON
            "<button class='btn btn-red' id='resetBtn' onclick='resetSystem()'>Reset System</button>"
        "</div>"
    "</div>"

    "<script>"
        // --- 1. HEX TO BYTES ---
        "function hexToBytes(hex) {"
            "if (hex.length % 2 !== 0) throw new Error('Odd hex length');"
            "var bytes = new Uint8Array(hex.length / 2);"
            "for (var i = 0; i < hex.length; i += 2) {"
                "bytes[i / 2] = parseInt(hex.substr(i, 2), 16);"
            "}"
            "return bytes;"
        "}"

        // --- 2. ROBUST SHA-256 ---
        "async function calculateHash(byteArray) {"
            "if (window.crypto && window.crypto.subtle) {"
                "const hashBuffer = await crypto.subtle.digest('SHA-256', byteArray);"
                "const hashArray = Array.from(new Uint8Array(hashBuffer));"
                "return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');"
            "}"
            "else {"
                "return sha256_fallback(byteArray);"
            "}"
        "}"
        
        "var sha256_fallback = function(data) {"
            "function rightRotate(value, amount) { return (value>>>amount) | (value<<(32 - amount)); };"
            "var mathPow = Math.pow; var maxWord = mathPow(2, 32); "
            "var i, j; var result = ''; var words = []; var asciiBitLength = data.length * 8;"
            "var hash = [0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A, 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19];"
            "var k = [0x428A2F98, 0x71374491, 0xB5C0FBCF, 0xE9B5DBA5, 0x3956C25B, 0x59F111F1, 0x923F82A4, 0xAB1C5ED5, 0xD807AA98, 0x12835B01, 0x243185BE, 0x550C7DC3, 0x72BE5D74, 0x80DEB1FE, 0x9BDC06A7, 0xC19BF174, 0xE49B69C1, 0xEFBE4786, 0x0FC19DC6, 0x240CA1CC, 0x2DE92C6F, 0x4A7484AA, 0x5CB0A9DC, 0x76F988DA, 0x983E5152, 0xA831C66D, 0xB00327C8, 0xBF597FC7, 0xC6E00BF3, 0xD5A79147, 0x06CA6351, 0x14292967, 0x27B70A85, 0x2E1B2138, 0x4D2C6DFC, 0x53380D13, 0x650A7354, 0x766A0ABB, 0x81C2C92E, 0x92722C85, 0xA2BFE8A1, 0xA81A664B, 0xC24B8B70, 0xC76C51A3, 0xD192E819, 0xD6990624, 0xF40E3585, 0x106AA070, 0x19A4C116, 0x1E376C08, 0x2748774C, 0x34B0BCB5, 0x391C0CB3, 0x4ED8AA4A, 0x5B9CCA4F, 0x682E6FF3, 0x748F82EE, 0x78A5636F, 0x84C87814, 0x8CC70208, 0x90BEFFFA, 0xA4506CEB, 0xBEF9A3F7, 0xC67178F2];"
            "var combined = new Uint8Array(data.length + 1 + 8 + (64 - (data.length + 9) % 64));"
            "combined.set(data); combined[data.length] = 0x80;"
            "var view = new DataView(combined.buffer); view.setUint32(combined.length - 4, asciiBitLength, false);"
            "for (i = 0; i < combined.length; i+=4) words[i>>2] = view.getUint32(i, false);"
            "for (j = 0; j < words.length;) {"
                "var w = words.slice(j, j += 16);"
                "var oldHash = hash;"
                "hash = hash.slice(0); "
                "for (i = 0; i < 64; i++) {"
                    "var i2 = i + j;"
                    "var w15 = w[i - 15], w2 = w[i - 2];"
                    "var a = hash[0], e = hash[4];"
                    "var temp1 = hash[7] + (rightRotate(e, 6) ^ rightRotate(e, 11) ^ rightRotate(e, 25)) + ((e&hash[5])^((~e)&hash[6])) + k[i] + (w[i] = (i < 16) ? w[i] : (w[i - 16] + (rightRotate(w15, 7) ^ rightRotate(w15, 18) ^ (w15>>>3)) + w[i - 7] + (rightRotate(w2, 17) ^ rightRotate(w2, 19) ^ (w2>>>10))) | 0);"
                    "var temp2 = (rightRotate(a, 2) ^ rightRotate(a, 13) ^ rightRotate(a, 22)) + ((a&hash[1])^(a&hash[2])^(hash[1]&hash[2]));"
                    "hash = [(temp1 + temp2)|0].concat(hash);"
                    "hash[4] = (hash[4] + temp1)|0;"
                "}"
                "for (i = 0; i < 8; i++) hash[i] = (hash[i] + oldHash[i])|0;"
            "}"
            "for (i = 0; i < 8; i++) {"
                "for (j = 3; j + 1; j--) {"
                    "var b = (hash[i]>>(j*8))&255;"
                    "result += ((b < 16) ? 0 : '') + b.toString(16);"
                "}"
            "}"
            "return result;"
        "};"

        "let isFlashing = false;"
        "let pollInterval = null;"
        
        "document.getElementById('fileInput').addEventListener('change', function(e) {"
            "let file = e.target.files[0];"
            "if (!file) return;"
            "let reader = new FileReader();"
            "reader.onload = function(e) {"
                "document.getElementById('hexInput').value = e.target.result;"
                "alert('File loaded! Click Upload & Verify to proceed.');"
            "};"
            "reader.readAsText(file);"
        "});"

        "function cleanHex(input) {"
            "let clean = input.replace(/0x/gi, '');"
            "clean = clean.replace(/[^0-9A-Fa-f]/g, '');"
            "return clean;"
        "}"

        "function uploadFirmware() {"
            "let raw = document.getElementById('hexInput').value;"
            "let hex = cleanHex(raw);"
            
            "if(hex.length % 2 !== 0 || hex.length === 0) { alert('Invalid Data (Odd length)! Check your input.'); return; }"
            "if(hex.length > 300000) { alert('File too large (>150KB binary)!'); return; }"
            
            "document.getElementById('uploadBtn').disabled = true;"
            "document.getElementById('uploadStatus').innerText = 'Calculating Hash...';"
            
            "setTimeout(async function() {"
                "try {"
                    "var rawBytes = hexToBytes(hex);"
                    "var hashHex = await calculateHash(rawBytes);"
                    "console.log('Client Hash:', hashHex);"

                    "document.getElementById('uploadStatus').innerText = 'Uploading...';"
                    
                    "fetch('/api/upload', {"
                        "method: 'POST',"
                        "headers: { 'X-Payload-SHA256': hashHex },"
                        "body: hex"
                    "})"
                    ".then(r => { if(r.ok) return r.json(); throw new Error(r.statusText); })"
                    ".then(d => {"
                        "document.getElementById('uploadStatus').innerText = 'Verified & Stored';"
                        "document.getElementById('ramSize').innerText = d.size;"
                        "document.getElementById('flashBtn').disabled = false;"
                        "document.getElementById('uploadBtn').disabled = false;"
                        "document.getElementById('totalBytes').innerText = d.size;"
                        "alert('Integrity Check PASSED! Firmware loaded into RAM.');"
                    "}).catch(e => {"
                        "document.getElementById('uploadStatus').innerText = 'Error';"
                        "document.getElementById('uploadBtn').disabled = false;"
                        "alert('Upload Failed: ' + e);"
                    "});"
                "} catch(err) {"
                    "alert('Error processing file: ' + err);"
                    "document.getElementById('uploadBtn').disabled = false;"
                "}"
            "}, 100);"
        "}"

        "function startFlash() {"
            "if(!confirm('Start BMS Update? Do not power off.')) return;"
            "isFlashing = true;"
            "document.getElementById('flashBtn').disabled = true;"
            "document.getElementById('uploadBtn').disabled = true;"
            "document.getElementById('hexInput').disabled = true;"
            "document.getElementById('fileInput').disabled = true;"
            "document.getElementById('resetBtn').disabled = true;" // Disable reset during flash
            "document.getElementById('sysState').innerText = 'Starting...';"
            
            "fetch('/api/flash', { method: 'POST' })"
            ".then(r => { if(r.ok) return r.json(); throw new Error('Busy'); })"
            ".then(d => {"
                "if(pollInterval) clearInterval(pollInterval);"
                "pollInterval = setInterval(pollStatus, 500);" 
            "}).catch(e => {"
                "alert('Could not start flash: ' + e);"
                "isFlashing = false;"
                "document.getElementById('flashBtn').disabled = false;"
                "document.getElementById('uploadBtn').disabled = false;"
                "document.getElementById('hexInput').disabled = false;"
                "document.getElementById('fileInput').disabled = false;"
                "document.getElementById('resetBtn').disabled = false;"
            "});"
        "}"

        "function resetSystem() {"
            "if(!confirm('Reset System and Clear Buffer?')) return;"
            "fetch('/api/reset', { method: 'POST' })"
            ".then(r => r.json())"
            ".then(d => {"
                "alert('System Reset!');"
                "window.location.reload();" // Simplest way to reset UI is reload
            "}).catch(e => alert('Reset Failed: ' + e));"
        "}"

        "function pollStatus() {"
            "fetch('/api/status')"
            ".then(r => r.json())"
            ".then(d => {"
                "document.getElementById('sysState').innerText = d.status;"
                "document.getElementById('sentBytes').innerText = d.sent;"
                "document.getElementById('totalBytes').innerText = d.total;"
                "let pct = 0;"
                "if(d.total > 0) pct = Math.round((d.sent / d.total) * 100);"
                "if(pct > 100) pct = 100;"
                "document.getElementById('progressBar').style.width = pct + '%';"
                "document.getElementById('progressText').innerText = pct + '%';"
                "if (d.busy === false && isFlashing) {"
                    "clearInterval(pollInterval);"
                    "isFlashing = false;"
                    "document.getElementById('uploadBtn').disabled = false;"
                    "document.getElementById('hexInput').disabled = false;"
                    "document.getElementById('fileInput').disabled = false;"
                    "document.getElementById('flashBtn').disabled = true;"
                    "document.getElementById('resetBtn').disabled = false;"
                    "if(d.status.includes('Success')) alert('Update Complete Successfully!');"
                    "else alert('Update Failed: ' + d.status);"
                "}"
            "}).catch(e => console.log('Poll error', e));"
        "}"
    "</script>"
"</body>"
"</html>";

#endif